# -*- coding: utf-8 -*-
"""
Created on Sat Jun 23 20:31:45 2018

@author: ashima.garg
"""

import os
import math

# DIRECTORY INFORMATION
ROOT_DIR = os.path.abspath('../')
DATA_DIR = os.path.join(ROOT_DIR, 'DATASET/')
OUT_DIR = os.path.join(ROOT_DIR, 'RESULT/')
MODEL_DIR = os.path.join(ROOT_DIR, 'MODEL/')

TRAIN_DIR = "train"
TEST_DIR = "test"

# RANDOM NUMBER GENERATOR INFORMATION
SEED = 128

# TRAINING INFORMATION
NUM_EPOCHS = 20
INITIAL_LEARNING_RATE = 0.0001

# IMAGE PROCESSING DETAILS
READ_SIZE = 242
INPUT_SIZE = 33
OUTPUT_SIZE = 21
SCALE = 3
DIM = 1
PAD = int((INPUT_SIZE - OUTPUT_SIZE)/2)
STRIDE = 14

# DATA INFORMATION
SUB_IMG = int(math.floor((READ_SIZE-INPUT_SIZE)/STRIDE) + 1)
NUM_SUBIMG = int(math.pow(SUB_IMG, 2))
BATCH_SIZE = 5
